/**
 * Problem 2 from Project Euler
 * 
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10
 * terms will be:
 * 	1,2,3,5,8,13,21,34,55,89 ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms
 * 
 * PLEASE NOTE
 * In order to compile you must have JDK installed on your machine
 * 
 * REGARDING THE PERFORMANCE
 * This is not the final version of the script, you can improve the algorithm by submitting pull request or issue on Github.
 * Feel free to ask for anything on Github.
 * 
 * @author Claudio Ludovico Panetta (@Ludo237)
 * @version 1.0.0
 *
 */
public class Problem_2 {


	public static void main(String[] args) {
		
	}

}
