#include <stdio.h>
#include <stdlib.h>
/********************************
 *
 * Problem 2 from Project Euler
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 *  
 *  1,2,3,5,8,21,34,55,89 ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-values terms
 *
 * PLEASE NOTE
 * In order to compile you must have gcc or similar
 *
 * REGARDING THE PERFORMANCE
 * This is not the final version of the script, you can improve the algorithm by submitting a pull request or an issue on Github.
 * Feel free to ask anything on Github.
 *
 * @author Claudio Ludovico Panetta(@Ludo237)
 * @version 1.0.0
 ********************************/

int array_sum(int array[]);

int main(int argc, char** argv)
{
    // Basically we shouldn't have a "Fixed" lenght for our algorithm
    int size = 32; // Fibonacci's numbers
    int pivots[2] = {1,2}; // First two pivots
    int fibonacci[sizeof(size)] = {0};
    int total = 0;

    // Iterating trough the size number
    for(int i = 0; i < size; i++)
    {
        if( i == 0 ) // The first number, we don't touch it
            fibonacci[i] = pivots[0];
        else if( i == 1) // Same for this
            fibonacci[i] = pivots[1];
        else // The fun part of the algorithm
        {
            fibonacci[i] = array_sum(pivots); // Using a custom array_sum in C
            pivots[0] = pivots[1];
            pivots[1] = fibonacci[i];
        }

        if( fibonacci[i] % 2 == 0) // This is even
            total += fibonacci[i];
    }
    
    // End of the algorithm
    return 0;
}

/***************
 *
 * array_sum()
 * Simple "hack" to sum array values
 * @param int array[]
 * @return int
 ***************/
int array_sum(int array[])
{
    int i, sum = 0;
    for(i = 0; i < 32; i++)
    {
        sum += array[i];
    }
    return sum;
}
